spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.iubeumzcznngczzrrqaa
spring.datasource.password=puXKFlZ0X9Slvk0e

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Supabase'deki verilerimizin/tablolarımızın silinmemesi için koruma
spring.jpa.hibernate.ddl-auto=none