spring.datasource.url=jdbc:postgresql://localhost:5432/isdemir_db
spring.datasource.username=postgres
spring.datasource.password=1234

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Local'deki DB şu an boş olduğu için tabloları Spring Boot otomatik kursun
spring.jpa.hibernate.ddl-auto=update

# Çalışan SQL sorgularını ekranda güzelce görelim
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
